### Problem Statement 1 :

Write a Python program using NumPy to analyze the grades of multiple students across different subjects.

Your program should:

Create a list of 5 student names and a list of 3 subjects.

Generate a 5×3 matrix of random integer grades between 60 and 100 using np.random.randint().

Display the grades matrix, student names, and subject names.

Compute and display:

The average grade for each student (row-wise mean).

The average grade for each subject (column-wise mean).

Print each student’s name along with their average grade (rounded to 1 decimal place).

Determine and print the top-performing student and their average score.


#### Step 1: Import NumPy and define student and subject lists

In [1]:
import numpy as np

student = ["Aditya","Vedant","Prapti","Sahili","Aniket"]
subject = ["Math","Science","English"]

#### Step 2: Generate a 5×3 matrix of random grades between 60 and 100

In [5]:
grades = np.random.randint(60,101,size=(5,3))
print(grades)

[[93 92 62]
 [74 92 64]
 [70 78 81]
 [89 98 73]
 [84 64 66]]


#### Step 3: Display the grades matrix, student names, and subject names

In [7]:
print("Subjects : ",subject)
print("Students : ",student)
print("Grades Matrix:\n :",grades)

Subjects :  ['Math', 'Science', 'English']
Students :  ['Aditya', 'Vedant', 'Prapti', 'Sahili', 'Aniket']
Grades Matrix:
 : [[93 92 62]
 [74 92 64]
 [70 78 81]
 [89 98 73]
 [84 64 66]]


#### Step 4: Compute average grade for each student (row-wise mean)

In [11]:
student_average = np.mean(grades,axis = 1)
#axis=1 means we compute the mean across columns (i.e., per student).
print("Average grade per student:",student_average)

Average grade per student: [82.33333333 76.66666667 76.33333333 86.66666667 71.33333333]


#### Step 5: Compute average grade for each subject (column-wise mean)

In [13]:
subject_average = np.mean(grades,axis = 0)
# axis=0 means we compute the mean across rows (i.e., per subject).
print("Average grade per subject: ",subject_average)

Average grade per subject:  [82.  84.8 69.2]


#### Step 6: Print each student’s name with their average grade (rounded)

In [14]:
print("\nStudent Averages:")
for name, avg in zip(student, student_average):
    print(f"{name} : {round(avg,1)}")


Student Averages:
Aditya : 82.3
Vedant : 76.7
Prapti : 76.3
Sahili : 86.7
Aniket : 71.3


#### Step 7: Determine and print the top-performing student

In [15]:
top_index = np.argmax(student_average)
top_student = student[top_index]
top_score = round(student_average[top_index],1)
# np.argmax() finds the index of the highest average.
# We use that index to get the student name and score.
print(F"Top-performing student : {top_student} with average score {top_score}")

Top-performing student : Sahili with average score 86.7


### Problem Statement 2:

Write a Python program using NumPy to perform analysis on sales data of different products over six months.

Your program should:

Create a list of 6 months (Jan–Jun) and 3 products (Product A, Product B, Product C).

Generate a 6×3 matrix of random sales figures (between 1000 and 5000) using np.random.randint().

Display the sales matrix clearly (Months × Products).

Calculate and display:

Total monthly sales (sum across products).

Total sales per product (sum across months).

Identify and display:

The best-performing month (highest total sales).

The best-selling product (highest cumulative sales).

#### Step 1: Import NumPy and define months and products

In [27]:
import numpy as np

months = ["Jan", "Feb", "Mar", "Apr", "May","June"]
products = ["Product A","Product B","Product C"]

#### Step 2: Generate a 6×3 matrix of random sales figures between 1000 and 5000

In [38]:
sales = np.random.randint(1000,5001,size = (6, 3))
print(sales)

[[4201 3473 3391]
 [4772 2133 3908]
 [4324 2621 1913]
 [3348 4717 3337]
 [1294 3379 1123]
 [4510 2696 2886]]


#### Step 3: Display the sales matrix clearly

In [39]:
print("Monts: ",months)
print("product: ", products)
print("\nSales Matrix (Months x products):\n", sales)

Monts:  ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'June']
product:  ['Product A', 'Product B', 'Product C']

Sales Matrix (Months x products):
 [[4201 3473 3391]
 [4772 2133 3908]
 [4324 2621 1913]
 [3348 4717 3337]
 [1294 3379 1123]
 [4510 2696 2886]]


#### Step 4: Calculate total monthly sales (sum across products)

In [42]:
monthly_totals = np.sum(sales,axis = 1)
print("Total Monthly Sales:\n")
for month, total in zip(months,monthly_totals):
    print(f"{month} : {total}")

Total Monthly Sales:

Jan : 11065
Feb : 10813
Mar : 8858
Apr : 11402
May : 5796
June : 10092


#### Step 5: Calculate total sales per product (sum across months)

In [43]:
product_totals = np.sum(sales, axis = 0)
print("\nTotal sales per product: ")
for product, total in zip(products, product_totals):
    print(f"{product} : {total}")


Total sales per product: 
Product A : 22449
Product B : 19019
Product C : 16558


#### Step 6: Identify the best-performing month

In [46]:
best_month_index = np.argmax(monthly_totals)
best_month = months[best_month_index]
best_month_sales = month_totals[best_month_index]

print(f"Best-performing Month: {best_month} with sales of {best_month_sales}")

Best-performing Month: Apr with sales of 11402


#### Step 7: Identify the best-selling product

In [51]:
best_product_index = np.argmax(product_totals)
best_product = products[best_product_index]
best_product_sales = product_totals[best_product_index]

print(f"Best-Selling product: {best_product} with total sales of {best_product_sales}")

Best-Selling product: Product A with total sales of 22449
