In [ ]:
#combining and splitting array

In [1]:
a = [30,40,50] #list
b = [5,5,3]
print(a+b)

[30, 40, 50, 5, 5, 3]


In [5]:
#Concatenate
import numpy as np
arr1 = np.array([30,40,50])
arr2 = np.array([5,5,3])
print(np.concatenate([arr1,arr2]))

[30 40 50  5  5  3]


In [6]:
import numpy as np
arr1 = np.array([[30,40],[50,10]])
arr2 = np.array([[5,5],[3,3]])
print(np.concatenate([arr1,arr2]))

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]]


In [10]:
print(np.concatenate([arr1,arr2],axis= 0))
print(np.concatenate([arr1,arr2],axis= 1))

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]]
[[30 40  5  5]
 [50 10  3  3]]


In [12]:
print(np.hstack([arr1,arr2])) #horizontal concatenation

[[30 40  5  5]
 [50 10  3  3]]


In [13]:
print(np.vstack([arr1,arr2])) #vertical concatenation

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]]


In [16]:
a = np.array([20,40,30,40,10,20])
print(np.array_split(a,3))

[array([20, 40]), array([30, 40]), array([10, 20])]


In [17]:
a = np.array([20,40,30,40,10,20])
b = np.array_split(a,3)
print(b[1])

[30 40]


In [19]:
a = np.array([20,40,30,40,10,20])
b = np.array_split(a,5)
print(b)

[array([20, 40]), array([30]), array([40]), array([10]), array([20])]


In [23]:
a = np.array([[20,40,30],[40,10,20]])
b = np.array_split(a,4)
print(b)

[array([[20, 40, 30]]), array([[40, 10, 20]]), array([], shape=(0, 3), dtype=int64), array([], shape=(0, 3), dtype=int64)]
