In [4]:
import numpy as np
arr = np.array([[10,20,30,40],[70,80,90,10],[30,40,50,60]])
print(arr)
print(type(arr))

[[10 20 30 40]
 [70 80 90 10]
 [30 40 50 60]]
<class 'numpy.ndarray'>


In [9]:
import numpy as np
arr = np.array([10,20,30,40])
print(arr[0:])
print(arr[:5])

[10 20 30 40]
[10 20 30 40]


In [30]:
import numpy as np
arr = np.array([[10,20,30,40],[50,60,70,80],[30,40,50,60]])
print(arr[0:2,0:2])
print("second and third value from first array",arr[0,1:3])
print("second and fourth value from second array",arr[1,2:4])
print("second value of the third array",arr[2,2])
print(np.shape(arr))
print(np.size(arr))
print(np.ndim(arr))  #dimension  of an array
print(arr.dtype) #datatype of element in an array

[[10 20]
 [50 60]]
second and third value from first array [20 30]
second and fourth value from second array [70 80]
second value of the third array 50
(3, 4)
12
2
int64
