In [1]:
import numpy as np
a = [30,40,50,60]
arr = np.array(a)
print(a)

[30, 40, 50, 60]


In [12]:
import numpy as np
a = [[30,40,50],[30,40,10]]
arr = np.array(a)
print(arr)
print(arr.shape)    #row,colum
print(len(arr))     #number of nested value
print(np.size(arr)) #number of elements
print(type(arr))    #data type of variable
print(arr.dtype)    #data type of array
print(arr.astype(float)) #conversion of data type

[[30 40 50]
 [30 40 10]]
(2, 3)
2
6
<class 'numpy.ndarray'>
int64
[[30. 40. 50.]
 [30. 40. 10.]]
