In [ ]:
#Addition and removing element in the array

In [31]:
import numpy as np

a = np.array([20,30,60,80])
print(np.append(a,90))

[20 30 60 80 90]


In [5]:
import numpy as np

a = np.array([[20,30],[60,80]]) # in 2d array
print(np.append(a,90))

[20 30 60 80 90]


In [6]:
import numpy as np

a = np.array([[20,30],[60,80]]) # in 2d array
print(np.append(a,[90,100]))

[ 20  30  60  80  90 100]


In [7]:
import numpy as np

a = np.array([20,30,60,80])
print(np.insert(a,1,50))

[20 50 30 60 80]


In [12]:
import numpy as np

a = np.array([[20,30],[60,80]])
print(np.insert(a,1,50))

[20 50 30 60 80]


In [14]:
print(np.insert(a,1,[50,60]))

[20 50 60 30 60 80]


In [10]:
print(np.insert(a,1,[50,60],axis = 0))

[[20 30]
 [50 60]
 [60 80]]


In [11]:
print(np.insert(a,1,[50,60],axis = 1))

[[20 50 30]
 [60 60 80]]


In [22]:
print(np.insert(a,[1,2],[50],axis = 0))
print(np.insert(a,[1,2],[50],axis = 1))

[[20 30]
 [50 50]
 [60 80]
 [50 50]]
[[20 50 30 50]
 [60 50 80 50]]


In [23]:
print(np.insert(a,[1,2],[50],axis = 0))

[[20 30]
 [50 50]
 [60 80]
 [50 50]]


In [26]:
print(a)
print(np.delete(a,1))

[[20 30]
 [60 80]]
[20 60 80]


In [29]:
print(a)
print()
print(np.delete(a,1,axis = 0))
print()
print(np.delete(a,1,axis = 1))

[[20 30]
 [60 80]]

[[20 30]]

[[20]
 [60]]
