In [3]:
#mathematical function anf function on array
import numpy as np

arr1 = np.array([30,40,60,20,10])
arr2 = np.array([30,20,10,20,20])
print(arr1+arr2)
print(np.add(arr1,arr2))

[60 60 70 40 30]
[60 60 70 40 30]


In [6]:
import numpy as np

arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[10,20]])
print(arr1+arr2)
print(np.add(arr1,arr2))

[[60 60]
 [30 30]]
[[60 60]
 [30 30]]


In [8]:
import numpy as np

arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[10,20]])
print(arr1/arr2)
print(np.divide(arr1,arr2))

[[1.  2. ]
 [2.  0.5]]
[[1.  2. ]
 [2.  0.5]]


In [11]:
arr1 = np.array([3,4,2,1])
arr2 = np.array(3)
print(np.power(arr1,arr2))

[27 64  8  1]


In [13]:
arr1 = np.array([9,16,4,1])
print(np.sqrt(arr1))

[3. 4. 2. 1.]
