In [5]:
import numpy as np

a = np.array([20,40,60,70])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.size(a))
print(np.mean(a))
print(np.cumsum(a)) #this means adding the current number to previous number

190
20
70
4
47.5
[ 20  60 120 190]


In [11]:
a = [100,150,199,200,250,130]
b = [10,50,30,40,30,10]

price = np.array(a)
quantity = np.array(b)
print(price,"\n",quantity)
print()
print(np.cumprod([price,quantity],axis = 0))

c = np.cumprod([price,quantity],axis = 0)
print("The sum of the total elements are ", c[1].sum())




[100 150 199 200 250 130] 
 [10 50 30 40 30 10]

[[ 100  150  199  200  250  130]
 [1000 7500 5970 8000 7500 1300]]
The sum of the total elements are  31270
